services:
  db:
    image: postgres:16-alpine
    container_name: tarea6_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_READER_PASSWORD: ${APP_READER_PASSWORD}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./db/reports_vw.sql:/docker-entrypoint-initdb.d/03-reports_vw.sql
      - ./db/indexes.sql:/docker-entrypoint-initdb.d/04-indexes.sql
      - ./db/roles.sql:/docker-entrypoint-initdb.d/05-roles.sql
      - ./db/set_app_password.sh:/docker-entrypoint-initdb.d/06-set_app_password.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: tarea6_app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      APP_PORT: ${APP_PORT:-3000}
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy